name: SpecLynx CLI full nightly build

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 4 * * *'

jobs:
  nightly-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.10.0
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint code
        run: npm run lint
      - name: Check TypeScript types
        run: npm run typescript:check-types
      - name: Execute tests
        run: npm test
